import type { Catalogue } from "./catalogue.js";

/**
 * The tile catalogue, generated from the art pack.
 *
 * Lives in the shared package because both sides need it: the editor to
 * draw a palette, and the server to write the tileset list into a saved
 * map. Reading it from the web app's public folder would work in
 * development and fail in a container that only ships the server.
 *
 * Regenerate with `node apps/web/scripts/build-catalogue.mjs` after
 * changing the art pack.
 */
export const TILESETS: Catalogue = [
  {
    key: "room-builder",
    name: "Walls & floors",
    file: "limezu/tiles/room-builder.png",
    columns: 76,
    rows: 113,
    firstGid: 1,
    structural: true,
  },
  {
    key: "generic",
    name: "Generic",
    file: "limezu/tiles/generic.png",
    columns: 16,
    rows: 78,
    firstGid: 8589,
    structural: false,
  },
  {
    key: "living-room",
    name: "Living room",
    file: "limezu/tiles/living-room.png",
    columns: 16,
    rows: 45,
    firstGid: 9837,
    structural: false,
  },
  {
    key: "bathroom",
    name: "Bathroom",
    file: "limezu/tiles/bathroom.png",
    columns: 16,
    rows: 56,
    firstGid: 10557,
    structural: false,
  },
  {
    key: "bedroom",
    name: "Bedroom",
    file: "limezu/tiles/bedroom.png",
    columns: 16,
    rows: 107,
    firstGid: 11453,
    structural: false,
  },
  {
    key: "classroom-library",
    name: "Classroom & library",
    file: "limezu/tiles/classroom-library.png",
    columns: 16,
    rows: 34,
    firstGid: 13165,
    structural: false,
  },
  {
    key: "music-sport",
    name: "Music & sport",
    file: "limezu/tiles/music-sport.png",
    columns: 16,
    rows: 48,
    firstGid: 13709,
    structural: false,
  },
  {
    key: "art",
    name: "Art",
    file: "limezu/tiles/art.png",
    columns: 16,
    rows: 7,
    firstGid: 14477,
    structural: false,
  },
  {
    key: "gym",
    name: "Gym",
    file: "limezu/tiles/gym.png",
    columns: 16,
    rows: 33,
    firstGid: 14589,
    structural: false,
  },
  {
    key: "fishing",
    name: "Fishing",
    file: "limezu/tiles/fishing.png",
    columns: 16,
    rows: 27,
    firstGid: 15117,
    structural: false,
  },
  {
    key: "birthday-party",
    name: "Birthday party",
    file: "limezu/tiles/birthday-party.png",
    columns: 12,
    rows: 7,
    firstGid: 15549,
    structural: false,
  },
  {
    key: "halloween",
    name: "Halloween",
    file: "limezu/tiles/halloween.png",
    columns: 16,
    rows: 61,
    firstGid: 15633,
    structural: false,
  },
  {
    key: "kitchen",
    name: "Kitchen",
    file: "limezu/tiles/kitchen.png",
    columns: 16,
    rows: 49,
    firstGid: 16609,
    structural: false,
  },
  {
    key: "conference-hall",
    name: "Conference Hall",
    file: "limezu/tiles/conference-hall.png",
    columns: 16,
    rows: 12,
    firstGid: 17393,
    structural: false,
  },
  {
    key: "basement",
    name: "Basement",
    file: "limezu/tiles/basement.png",
    columns: 16,
    rows: 50,
    firstGid: 17585,
    structural: false,
  },
  {
    key: "christmas",
    name: "Christmas",
    file: "limezu/tiles/christmas.png",
    columns: 16,
    rows: 17,
    firstGid: 18385,
    structural: false,
  },
  {
    key: "grocery-store",
    name: "Grocery store",
    file: "limezu/tiles/grocery-store.png",
    columns: 16,
    rows: 78,
    firstGid: 18657,
    structural: false,
  },
  {
    key: "upstairs-system",
    name: "Upstairs system",
    file: "limezu/tiles/upstairs-system.png",
    columns: 16,
    rows: 27,
    firstGid: 19905,
    structural: false,
  },
  {
    key: "jail",
    name: "Jail",
    file: "limezu/tiles/jail.png",
    columns: 16,
    rows: 45,
    firstGid: 20337,
    structural: false,
  },
  {
    key: "hospital",
    name: "Hospital",
    file: "limezu/tiles/hospital.png",
    columns: 16,
    rows: 110,
    firstGid: 21057,
    structural: false,
  },
  {
    key: "japanese-interiors",
    name: "Japanese interiors",
    file: "limezu/tiles/japanese-interiors.png",
    columns: 16,
    rows: 32,
    firstGid: 22817,
    structural: false,
  },
  {
    key: "clothing-store",
    name: "Clothing Store",
    file: "limezu/tiles/clothing-store.png",
    columns: 16,
    rows: 67,
    firstGid: 23329,
    structural: false,
  },
  {
    key: "museum",
    name: "Museum",
    file: "limezu/tiles/museum.png",
    columns: 16,
    rows: 122,
    firstGid: 24401,
    structural: false,
  },
  {
    key: "tv-film-studio",
    name: "TV & film studio",
    file: "limezu/tiles/tv-film-studio.png",
    columns: 16,
    rows: 14,
    firstGid: 26353,
    structural: false,
  },
  {
    key: "ice-cream-shop",
    name: "Ice Cream Shop",
    file: "limezu/tiles/ice-cream-shop.png",
    columns: 16,
    rows: 17,
    firstGid: 26577,
    structural: false,
  },
  {
    key: "shooting-range",
    name: "Shooting Range",
    file: "limezu/tiles/shooting-range.png",
    columns: 16,
    rows: 5,
    firstGid: 26849,
    structural: false,
  },
  {
    key: "condominium",
    name: "Condominium",
    file: "limezu/tiles/condominium.png",
    columns: 16,
    rows: 19,
    firstGid: 26929,
    structural: false,
  },
];
